// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh7sqRtHHGOB87wCRE-JK-0ijYTz3aNYY',
    appId: '1:132338598437:web:988709b14d773c8cf3f5cc',
    messagingSenderId: '132338598437',
    projectId: 'my-portfolio-3e120',
    authDomain: 'my-portfolio-3e120.firebaseapp.com',
    storageBucket: 'my-portfolio-3e120.appspot.com',
    measurementId: 'G-DS827DC549',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6F1Xg5FMqJPljc4BwGUQB4pg60wbLkoo',
    appId: '1:132338598437:android:27b21c8f07c68da9f3f5cc',
    messagingSenderId: '132338598437',
    projectId: 'my-portfolio-3e120',
    storageBucket: 'my-portfolio-3e120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRVutQaPclKD1eWlDY-DggYZMpH5QfC98',
    appId: '1:132338598437:ios:1bac1dd4887edea8f3f5cc',
    messagingSenderId: '132338598437',
    projectId: 'my-portfolio-3e120',
    storageBucket: 'my-portfolio-3e120.appspot.com',
    iosBundleId: 'com.example.mysite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRVutQaPclKD1eWlDY-DggYZMpH5QfC98',
    appId: '1:132338598437:ios:1bac1dd4887edea8f3f5cc',
    messagingSenderId: '132338598437',
    projectId: 'my-portfolio-3e120',
    storageBucket: 'my-portfolio-3e120.appspot.com',
    iosBundleId: 'com.example.mysite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh7sqRtHHGOB87wCRE-JK-0ijYTz3aNYY',
    appId: '1:132338598437:web:c44e290ee3607d46f3f5cc',
    messagingSenderId: '132338598437',
    projectId: 'my-portfolio-3e120',
    authDomain: 'my-portfolio-3e120.firebaseapp.com',
    storageBucket: 'my-portfolio-3e120.appspot.com',
    measurementId: 'G-5N2HJ3FEH2',
  );
}
