// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc3L_ikKCVWprYiB_5tXiVWk2giWWeCcg',
    appId: '1:1063471690216:web:7466698bcacdbaaa14f45d',
    messagingSenderId: '1063471690216',
    projectId: 'my-portfolio-8ed94',
    authDomain: 'my-portfolio-8ed94.firebaseapp.com',
    storageBucket: 'my-portfolio-8ed94.appspot.com',
    measurementId: 'G-1KK2C872XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXmrDQP1Zarpys4FuZMUXMeSepRL-NCa8',
    appId: '1:1063471690216:android:246e80a82ff348aa14f45d',
    messagingSenderId: '1063471690216',
    projectId: 'my-portfolio-8ed94',
    storageBucket: 'my-portfolio-8ed94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHX20yOKcN4UJNAuOHXzG3ebz9Wg4tYmE',
    appId: '1:1063471690216:ios:37c231932b758c7614f45d',
    messagingSenderId: '1063471690216',
    projectId: 'my-portfolio-8ed94',
    storageBucket: 'my-portfolio-8ed94.appspot.com',
    iosBundleId: 'com.example.mysite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHX20yOKcN4UJNAuOHXzG3ebz9Wg4tYmE',
    appId: '1:1063471690216:ios:37c231932b758c7614f45d',
    messagingSenderId: '1063471690216',
    projectId: 'my-portfolio-8ed94',
    storageBucket: 'my-portfolio-8ed94.appspot.com',
    iosBundleId: 'com.example.mysite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc3L_ikKCVWprYiB_5tXiVWk2giWWeCcg',
    appId: '1:1063471690216:web:6d1f7b0f80f873af14f45d',
    messagingSenderId: '1063471690216',
    projectId: 'my-portfolio-8ed94',
    authDomain: 'my-portfolio-8ed94.firebaseapp.com',
    storageBucket: 'my-portfolio-8ed94.appspot.com',
    measurementId: 'G-7CFXE5XLVB',
  );
}
